# Setup
title:               Ritesh Dhemla
tagline:             ''
description:         ''
url:                 riteshdhemla.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ritesh Dhemla
  url:               https://github.com/riteshdhemla
  email:             riteshdhemla@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
